# Generated by Django 2.2.19 on 2021-03-19 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('key', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('POL', 'Politics News'), ('ART', 'Art News'), ('TECH', 'Technology News'), ('TRIVIA', 'Trivial News')], max_length=20)),
                ('region', models.CharField(choices=[('UK', 'UK News'), ('EU', 'European News'), ('W', 'World News')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('details', models.CharField(max_length=512)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space.Authors', to_field='username')),
            ],
        ),
    ]
